# Generated by Django 5.1.3 on 2024-12-20 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
