# Generated by Django 5.1.3 on 2024-12-26 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0009_alter_profile_image_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default.jpg/', upload_to='profile_pics'),
        ),
    ]
