# Generated by Django 5.1.3 on 2025-01-21 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0014_ratingreview_review_image'),
        ('userauths', '0016_alter_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='saved_restaurants',
            field=models.ManyToManyField(blank=True, related_name='saved_by', to='rest.restaurant'),
        ),
    ]
