# Generated by Django 5.1.3 on 2024-12-28 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0004_alter_restaurant_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='image',
            field=models.ImageField(default='restaurant_images/starters-logo (2).png', upload_to='restaurant_images'),
        ),
    ]
