# Generated by Django 5.1.3 on 2024-12-28 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0005_alter_restaurant_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='image',
            field=models.ImageField(default='restaurant_images/default-rest.png', upload_to='restaurant_images'),
        ),
    ]
