# Generated by Django 5.1.3 on 2024-12-31 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0007_remove_restaurant_average_cost_for_two_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='distance',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
    ]
