# Generated by Django 5.1.3 on 2025-01-20 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0011_remove_restaurant_tags_tag_restaurants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='restaurants',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='restaurants', to='rest.tag'),
        ),
    ]
