# Generated by Django 5.1.3 on 2025-01-21 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0012_remove_tag_restaurants_restaurant_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='image',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='restaurant_images'),
        ),
    ]
