# Generated by Django 5.1.3 on 2025-01-21 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0013_remove_restaurant_image_restaurant_main_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratingreview',
            name='review_image',
            field=models.ImageField(blank=True, null=True, upload_to='review_images'),
        ),
    ]
